#!/usr/bin/env sh

# Setup.
VERSION="0.1.1"

version() {
  printf "gh-fire version %s\n" "$VERSION"
  git --version
  gh version
}

# Helpers.
current_branch() {
  basename "$(git symbolic-ref HEAD)"
}

current_epoch() {
  date +%s
}

user_email() {
  git config user.email
}

new_branch() {
  echo "fire/${1:-$(current_branch)}-$(current_epoch)"
}

fire() {
  initial_branch="$(current_branch)"

  git checkout -b "$(new_branch)"

  # cd to git root directory
  cd "$(git rev-parse --show-toplevel)"

  git add -A

  if [ -z "$1" ]; then
    message="Fire! $(current_branch)."
  else
    message="$*"
  fi

  git commit -m "$message" --no-verify

  for remote in $(git remote); do
    git push --no-verify --set-upstream "${remote}" "$(current_branch)" || true
  done

  if [ "$(git stash list)" != '' ]; then
    for sha in $(git rev-list -g stash); do
      git push --no-verify origin "$sha":refs/heads/"$(current_branch $initial_branch)"-stash-"$sha"
    done
  fi

  printf "\n\nTO THE FIRE EXIT!!!\n"
}

display_help() {
  cat <<-EOF

  usage:
    gh fire [options] [COMMAND] [args]

  commands:
    gh fire                        Add, commit, and push to remote in case of fire
    gh fire <message>              Execute gh-fire with <message> for commit message


  options:
    -V, --version                   Output current version of gh-fire
    -h, --help                      Display this help information

EOF
  exit 0
}

case $1 in
-V | --version)
  version
  exit 0
  ;;
-h | --help)
  display_help
  exit 0
  ;;
esac

fire "$@"
